### ISSUE TITLE
How to build a universal binary on  M1 mac that could run on Intel Macs as well?

### ISSUE THREAD

**Issue by YonghuiDong** [zarathucorp/shiny-electron-template-m1-2023#3]
Dear Kim,

Do you have any idea on how to build a universal binary on  M1 mac that could run on Intel Macs as well? 

The Electron app built following your method only runs on M1 Mac.

Thanks.

Dong

**Comment by jhk0530** [comment]
Hello, 

I can't verify this because I don't have inter mac, but it's possible. 

change `get-r-mac.sh` code (line 11), and it should work.

```
https://cloud.r-project.org/bin/macosx/big-sur-arm64/base/R-4.2.2-arm64.pkg 
```

to 

```
https://cloud.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.3.1-x86_64.pkg
```

**big-sur-arm64** (m1) to **big-sur-x86_64** (intel) 

Since 4.3.1 is latest version (for me) if you want access futher version, you also need to change it.

> Note, you should synch version of R.

I think other doesn't effected from version of OS (at least for mac)

Thanks.

**Comment by YonghuiDong** [comment]
Daer Kim,

Thanks a lot for your prompt help. I thought there is a way to build a universal binary on M1.

I have tried the same way you provided previously. But I was not able to install packages.

So I change the `add-cran-binary-pkg.r` from:

```r
if (dir.exists("r-mac")) {
  install_bins(
    cran_pkgs = cran_pkgs, library_path = file.path("r-mac", "library"),
    type = "mac.binary.big-sur-arm64", decompress = untar
  )
}
```

to 

```r
if (dir.exists("r-mac")) {
  install_bins(
    cran_pkgs = cran_pkgs, library_path = file.path("r-mac", "library"),
    type = "mac.binary.big-sur-x86_64", decompress = untar
  )
}
```

The R package can be installed, but when I start the app, I got the follow error:

> Fatal error: unable to open the base package

So I manually copy and paste all the R packages. This time it worked, but `electron-forge make` did not work, and I got this error:

>✖ Finalizing package
        › /var/folders/zt/wz423bws5dgffvp0_wbslsz00000gn/T/electron-packager/darwin-x64/cardinal-darwin-x64-W6Eb18/Electron.a…

I think it is still R package installation issue.

Best regards,
Dong

**Comment by jhk0530** [comment]
I understand your situation as

- R successfully installed using `get-r-mac.sh`.
- your shiny app's CRAN package has installed as binary in `r-mac/library`

- but **base package has error** and **electron-forge make failed**

I think you may have problem in installing R. 

since `Base` related to it rather than r-package install.

so I guess you should check your working directory.  ( recommend to clear all and restart one, literally I deleted directory more than 10 times at first build 😭)

--- 

And for `electron-forge make`, I'm not sure whether I can help that much, since I don't have any clue or experience with electron ( I didn't changed from previous work )

but we can start with running shiny app first

**Comment by jhk0530** [comment]
If an Electron application is built on an M1 Mac and packaged as a ZIP file, 

which is assumed to support universal formats as mentioned in the [Electron Forge documentation](https://www.electronforge.io/config/makers/zip), 

It may not be compatible with Windows systems ( I checked )

Therefore, it is also likely that **an application built on an M1 Mac for Intel Macs might face compatibility issues.**

not sure for reason but I recommend to build with in intel mac's
